# Generated by Django 3.2.13 on 2022-06-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
